language: python
python:
  - "3.4"
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y gfortran liblapack-dev
    - sudo apt-get install -y python-numpy python-scipy
    - sudo apt-get install -y libhdf5-serial-dev netcdf-bin libnetcdf-dev 
    - sudo apt-get install -y libfreetype6-dev libpng-dev
    - sudo apt-get install -y ffmpeg libav-tools
    - pip install -U pip
# Use Miniconda for faster building
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
# Debugging
    - conda info -a
# command to install dependencies
install: 
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pandas statsmodels
    - source activate test-environment
    #- travis_wait pip install -r requirements.txt
    - pip install -e .
# command to run tests
script: 
    - py.test
#after_success:
#    - coveralls
