language: python
python:
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gfortran libopenblas-dev liblapack-dev
  - sudo apt-get install -y python-numpy python-scipy
  - sudo apt-get install -y libhdf5-serial-dev netcdf-bin libnetcdf-dev
# command to install dependencies
install: 
    - pip install -r requirements.txt
    - pip install -e .
# command to run tests
script: py.test
